<div class="wrapper">
	<div class="row">
		<div class="twelve columns">
			<h2>Banco de Horas</h2>
		</div>
	</div>
	<div class="row">
		<div class="nine columns"><!--icon-user-add-->
			<div class="medium info btn icon-left entypo icon-user-add">
				<a href="#">
					Novo Aluno
				</a>
			</div>
		</div>
		<div class="three columns field">
			<input class="input" type="text" placeholder="Pesquisar" />
		</div>
	</div>
	<div class="row">
		<div class="twelve columns">
			<table class="rounded">
				<thead>
					<tr>
						<th style="width:10%">Matrícula</th>
						<th>Nome do aluno</th>
						<th style="width:60%">Ações</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><a href="#">042112004</a></td>
						<td>Fulano da Silva Sauro</td>
						<td>
							<div class="medium secondary btn icon-left entypo icon-clock">
								<a href="#">
									Gerenciar Horas
								</a>
							</div>
							<div class="medium secondary btn icon-left entypo icon-newspaper">
								<a href="#">
									Histórico
								</a>
							</div>
							<div class="medium secondary btn icon-left entypo icon-pencil">
								<a href="#">
									Editar
								</a>
							</div>
							<div class="medium danger btn icon-left entypo icon-cancel">
								<a href="#">
									Deletar
								</a>
							</div>
						</td>
					</tr>
				</tbody>
			</table>
		</div>		
	</div>
	<div class="row">
		<div class="centered two columns">
    			<li class="default badge">&laquo;</li>
			  	<li class="default badge">1</li>
			  	<li class="primary badge">2</li>
			  	<li class="default badge">3</li>
  		</div>		
	</div>
</div>