<div class="wrapper">
	<div class="row">
		<div class="twelve columns">
			<h2>Bla bla bla</h2>
		</div>
	</div>
	<div class="row">
		<div class="six columns">
			aaa
		</div>
		<div class="six columns">
			aaab
		</div>
	</div>
	<div class="row">
		<div class="twelve columns">
			<table class="rounded">
				<thead>
					<tr>
						<th>Header</th>
						<th>Header</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Lorem ipsum</td>
						<td>This is a slightly longer block of content to show how the cells will wrap when necessary</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>